default: &default
  adapter: mysql2
  encoding: utf8
  database: nuuvem
  username: root
  password: nuuvem
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: nuuvem

test:
  <<: *default
  database: nuuvem

production:
  <<: *default
  database: nuuvem
